In [1]:
from mnist_loader import load_mnist
from image_ops import normalize_image_array
from models import SingleLayerNet
import numpy as np

In [2]:
x_train, x_test, t_train, t_test = load_mnist()

Just wait a sec. The data is loading...

Converting train-images.idx3-ubyte to NumPy Array ...
Done
Converting t10k-images.idx3-ubyte to NumPy Array ...
Done
Converting train-labels.idx1-ubyte to NumPy Array ...
Done
Converting t10k-labels.idx1-ubyte to NumPy Array ...
Done
Data has been successfully loaded!



In [3]:
target_idx = np.random.randint(low=0, high=60000, size=500)
x_train_sample = x_train[target_idx]
t_train_sample = t_train[target_idx]

# It is important to normalize the input space alongside each dimension.
x_train_sample = normalize_image_array(x_train_sample)

In [4]:
# a possibly simplest model: a linear regression

net = SingleLayerNet(num_input_node=784, num_w1_node=10, weight_init_std=0.01)

In [5]:
net.predict(x_train_sample)

array([[0.10213739, 0.09170575, 0.09912476, ..., 0.10026855, 0.09975905,
        0.09467193],
       [0.09849213, 0.09645059, 0.10257235, ..., 0.1024126 , 0.0927495 ,
        0.1115425 ],
       [0.09968535, 0.08708853, 0.10256875, ..., 0.10887607, 0.1021647 ,
        0.10298293],
       ...,
       [0.11280495, 0.07537297, 0.08789325, ..., 0.12226935, 0.09957879,
        0.08879567],
       [0.11342195, 0.10314502, 0.10085601, ..., 0.10001175, 0.09048792,
        0.09304304],
       [0.1010212 , 0.09366038, 0.10067017, ..., 0.10219381, 0.1029399 ,
        0.09962842]], shape=(500, 10))

In [6]:
net.accuracy(x_train_sample, t_train_sample)

np.float64(0.126)

In [7]:
net.loss(x_train_sample, t_train_sample)

np.float64(2.304509265717553)

In [8]:
net.gradient(x_train_sample, t_train_sample)

Calculating numerical gradient takes a while. Please be patient!


(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], shape=(784, 10)),
 array([ 0.00810379, -0.02222346, -0.00901784,  0.02206509,  0.00566416,
        -0.00692832, -0.00522616, -0.03637859,  0.00909058,  0.03485075]))